baseURL = "https://ctrlplusrevise.com"
title = "Ctrl + Revise"
enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = ["github.com/onweru/compose"] # edit this if you'ld rather use a fork of this repo
# theme = "compose"
enableGitInfo = true

# disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]

[params]
author = "Michael Salmons"
favicon = "/images/favicon.ico"
site_logo = "/images/logo.png"